### ISSUE TITLE
Exception during teardown

### ISSUE THREAD

**Issue by chipbell4** [Kidapt/springroll-kidaptive-plugin#1]
It looks like `teardown` is expecting `flushEvents()` to return a promise, on [this line](https://github.com/Kidapt/springroll-kidaptive-plugin/blob/master/src/js/main/KidaptiveAlpPlugin.js#L134)

However, from what I see in the code base, it doesn't look [that function](https://github.com/Kidapt/kidaptive-sdk-js/blob/a252c3b6f651b5aa978f4cd3dea24fd0d906ef4b/src/ts/main/kidaptive_event_manager.ts#L254) returns a promise (it's declared as `void`).

**Comment by sliu198** [comment]
Nice catch! Is this causing Springroll to crash? I'm currently working on some major changes to the SDK, so I'd like to release a fix with the new version. But if it's causing instability in Springroll, I'll release a patch ASAP

**Comment by chipbell4** [comment]
Yeah, it's failing somewhere in the teardown cycle (don't have the game right in front of me, so I can't remember exactly where).

It's not terribly urgent because the page closes either way, and the game's in beta anyways. More than likely, once you get those updates set I'll update the API calls in the game and all will be well.

Thanks!
